### ISSUE TITLE
Get PHPUnit and TravisCI into a not-💩 state.

### ISSUE THREAD

**Issue by mdwheele** [mdwheele/swotphp#12]
Hello fellow Hacktoberists!

This might be a *little* more complex to start with, but here goes.

So many years ago, this project started on some ancient version of PHPUnit and it looks like the TravisCI configuration has never run tests anyway so... while there *are* PHPUnit tests in the `/tests` directory and I **know** they've previously been executed... in 2019, TravisCI isn't executing them and they still use `PHPUnit_Framework_Testcase` (gross).

So... let's tackle the following together:

- [ ] Make `phpunit/phpunit` a development dependency of the project.
- [ ] Fix all occurrences of `PHPUnit_Framework_Testcase` (and any other issues that arise from upgrading PHPUnit).
- [ ] Run the tests on TravisCI.
- [ ] Drop support for PHP 5.6 and make sure tests run on PHP 7.2, 7.3 and 7.4. If you don't want to spend a ton of time fixing issues in `/src` (if any), that's cool. We'll get your PR merged and I can take care of that myself or open another #Hacktoberfest issue :grin: 

If you're feeling heroic, ping me and you'll be that much closer to a free t-shirt.

**Comment by Jaspaul** [comment]
I'll take this for a spin. :)

**Comment by Jaspaul** [comment]
@mdwheele I gave it a shot. Looks like this works just fine with 7.2 and 7.3, however there are test failures with 7.4.

Anyhow my PR enables testing on all three, allowing failures on 7.4.
