### ISSUE TITLE
Update domain list for the first time in a long time.

### ISSUE THREAD

**Issue by mdwheele** [mdwheele/swotphp#13]
Hello fellow Hacktoberists!

This is an easy one. 

Basically, we just need someone to submit a PR with the latest changes from our upstream data source. We even have a wonderful PHP script that does this work for you. It requires that `php-curl` and `php-zip` be installed!

Simply run `php bin/updateDomains.php` and submit a pull request that includes all changes to files inside the `/domains` directory.

Thanks!

**Comment by Pen-y-Fan** [comment]
I'm happy to pick this up

**Comment by GueGuerreiro** [comment]
Sorry @Pen-y-Fan, seems we both picked it up at about the same time :grimacing:

**Comment by Pen-y-Fan** [comment]
No problem, it was interesting ;)

**Comment by mdwheele** [comment]
Hey @Pen-y-Fan! If you want to take a crack at #12, go for it! If you only have time to do part of it, that's totally cool.
